// <auto-generated />
using System;
using MPIS.Device.RepositoryModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MPIS.Device.RepositoryModel.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MPIS.Device.DomainModel.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComputerName");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("EmailUser");

                    b.Property<string>("MAC");

                    b.Property<int>("TypeSO");

                    b.Property<DateTime?>("Updated");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MAC");

                    b.HasIndex("UserId");

                    b.ToTable("Devices","Core");
                });

            modelBuilder.Entity("MPIS.Device.DomainModel.Hardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Description");

                    b.Property<string>("Device");

                    b.Property<Guid?>("DeviceUnitId");

                    b.Property<string>("MACDevice");

                    b.Property<string>("Path");

                    b.Property<int>("TypeHardware");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUnitId");

                    b.HasIndex("MACDevice");

                    b.ToTable("Hardwares","Core");
                });

            modelBuilder.Entity("MPIS.Device.DomainModel.OperativeSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("DeviceId");

                    b.Property<string>("MACDevice");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MACDevice");

                    b.ToTable("OperativeSystems","Core");
                });

            modelBuilder.Entity("MPIS.Device.DomainModel.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<Guid?>("DeviceId");

                    b.Property<string>("MACDevice");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MACDevice");

                    b.ToTable("Softwares","Core");
                });

            modelBuilder.Entity("MPIS.Device.DomainModel.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Email");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users","Extermal");
                });

            modelBuilder.Entity("MPIS.Device.DomainModel.Device", b =>
                {
                    b.HasOne("MPIS.Device.DomainModel.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MPIS.Device.DomainModel.Hardware", b =>
                {
                    b.HasOne("MPIS.Device.DomainModel.Device", "DeviceUnit")
                        .WithMany("Hardwares")
                        .HasForeignKey("DeviceUnitId");
                });

            modelBuilder.Entity("MPIS.Device.DomainModel.OperativeSystem", b =>
                {
                    b.HasOne("MPIS.Device.DomainModel.Device", "Device")
                        .WithMany("OperativeSystems")
                        .HasForeignKey("DeviceId");
                });

            modelBuilder.Entity("MPIS.Device.DomainModel.Software", b =>
                {
                    b.HasOne("MPIS.Device.DomainModel.Device", "Device")
                        .WithMany("Softwares")
                        .HasForeignKey("DeviceId");
                });
#pragma warning restore 612, 618
        }
    }
}
